title: 战略方向hahhahah
sections:
  - section: 第一部分-企业战略
    questions:
      - question: 企业愿景、使命、价值观实施现状是
        type: radio
        seq: 1.1
        options:
          - 筹备中
          - 刚启动
          - 实施2年以内
          - 实施2年以上
      - question: 您认为企业发展至今最主要的成功因素是什么
        seq: 1.2
        type: radio
        options:
          - 企业家能力与魄力
          - 公司领导层非常团结、务实
          - 应对市场的灵活的管理机制和创新能力
          - 优秀的企业文化
          - 对人才的高度重视
          - 诚信经营
          - 良好的宏观环境和政策支持
          - 其他：____
      - question: 您对公司3年之后的前景有什么看法？
        seq: 1.3
        type: radio
        options:
          - 坚信有更好发展
          - 能维持适当发展
          - 存在潜在的危机
          - 无法判断
          - 没有考虑过
      - question: 您认为是否有必要让公司的每一位员工充分了解企业的发展规划
        seq: 1.4
        type: radio
        options:
          - 非常必要
          - 比较重要
          - 一般
          - 不太重要
          - 不重要
      - question: 您认为公司的人际关系
        type: radio
        seq: 1.5
        options:
          - 很好
          - 比较融洽
          - 不好不坏
          - 较差
          - 很差
      - question: 您对公司管理层的信任度如何
        type: radio
        seq: 1.6
        options:
          - 逐步增强
          - 逐步下降
          - 没变化
          - 不好说
      - question: 您认为将您的建议递交给公司管理层会起到作用吗
        type: radio
        seq: 1.7
        options:
          - 很有意义
          - 比较有意义
          - 不太有意义
          - 没有实际意义
          - 应该有作用
      - question: 公司战略部门规模如何
        type: radio
        seq: 1.8
        options:
          - 无
          - 1-3人
          - 4-6人
          - 7-10人
          - 10-15人
          - 15-50人
          - 50人+
      - question: 对战略到财务指标的分解体系评价
        type: radio
        seq: 1.9
        options:
          - 对应性高且易操作，易考核
          - 有较好的对应性，能够形成较好的年度预算
          - 对应性不强或考核存在一定困难，战略对财务预算指导性一般
          - 战略与财务指标联系较弱
          - 战略未被分解为财务指标且没有影响年度预算
      - question: 对战略到财务指标的分解体系评价
        type: radio
        seq: 1.10
        options:
          - 成熟且高效
          - 能够对战略执行完成度进行一定的评价
          - 战略执行评价不够及时或不够准确，但仍有一定参考意义
          - 没有完整的战略执行评价体系，不定期进行评价，结果参考意义较弱
          - 无战略执行评价体系
  - section: 第二部分-流程管理
    questions:
      - question: 您认为公司在以下现象中哪些比较突出？（多选题，不限选项）
        seq: 2.1
        type: checkbox
        options:
          - 部门职责重叠
          - 部门职能空白
          - 部门设置不当
          - 职责界定不清
          - 岗位设置不当
          - 岗位职责不清
          - 流程不合理	制度不健全
      - question: 您认为制定的工作计划有作用吗？
        type: radio
        seq: 2.2
        options:
          - 非常有用
          - 比较有用
          - 计划赶不上变化
          - 基本没用
      - question: 您认为公司在以下现象中哪些比较突出？（多选题，不限选项）
        seq: 2.3
        type: checkbox
        options:
          - 管理程序很乱
          - 缺乏规范管理
          - 上下级缺乏沟通
          - 管理制度欠缺
          - 经常不知道应该向谁汇报
          - 没人愿意拍板决策
          - 工作缺乏计划
          - 管理粗暴
          - 领导经常交办事项但却不问结果
          - 时间观念差
          - 员工流失率太高
          - 招工困难
          - 工资不合理
          - 没有合理的激励与发展机制
          - 部门本位主义严重
          - 内部沟通不畅
          - 业余活动太少
          - 食堂伙食单调
          - 公司内部有小团体
          - 领导的许诺兑现的少或迟缓
          - 许多建议或待批的报告石沉大海
      - question: 对公司现阶段架构，各项业务流程简洁清晰程度，部门间责权利划分的评价
        type: radio
        seq: 2.4
        options:
          - 非常好
          - 比较好
          - 一般
          - 比较差
          - 非常差
